"""Simplify UserYoutubeLog: remove total_seconds and progress_percent

Revision ID: 0c7db2cc67d8
Revises: 3425762c3afe
Create Date: 2026-01-24 23:12:59.672561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7db2cc67d8'
down_revision: Union[str, Sequence[str], None] = '3425762c3afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_youtube_logs', 'total_seconds')
    op.drop_column('user_youtube_logs', 'progress_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_youtube_logs', sa.Column('progress_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_youtube_logs', sa.Column('total_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
