"""Add game_character table

Revision ID: 0f7c34a2f782
Revises: 51d6f3c9b2f3
Create Date: 2026-02-08 18:50:16.073855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7c34a2f782'
down_revision: Union[str, Sequence[str], None] = '51d6f3c9b2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('max_mp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_game_character_id'), 'game_character', ['id'], unique=False)
    op.drop_column('novels', 'character_descriptions')
    op.drop_column('novels', 'thumbnail_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('thumbnail_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('novels', sa.Column('character_descriptions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_game_character_id'), table_name='game_character')
    op.drop_table('game_character')
    # ### end Alembic commands ###
