"""add_channel_id_to_youtube_list

Revision ID: 10c8c4a3bc49
Revises: d20d626e5206
Create Date: 2026-01-25 09:02:00.919353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c8c4a3bc49'
down_revision: Union[str, Sequence[str], None] = 'd20d626e5206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_list', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_list', 'channel_id')
    # ### end Alembic commands ###
