"""Add UserYoutubeLog table

Revision ID: 3425762c3afe
Revises: e376faf04195
Create Date: 2026-01-24 22:56:07.087273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3425762c3afe'
down_revision: Union[str, Sequence[str], None] = 'e376faf04195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_youtube_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('watched_seconds', sa.Integer(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_youtube_logs_id'), 'user_youtube_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_youtube_logs_user_id'), 'user_youtube_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_youtube_logs_video_id'), 'user_youtube_logs', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_youtube_logs_video_id'), table_name='user_youtube_logs')
    op.drop_index(op.f('ix_user_youtube_logs_user_id'), table_name='user_youtube_logs')
    op.drop_index(op.f('ix_user_youtube_logs_id'), table_name='user_youtube_logs')
    op.drop_table('user_youtube_logs')
    # ### end Alembic commands ###
