"""Remove YoutubeRSS and enhance YoutubeChannel

Revision ID: 35d22167c2ae
Revises: 4506a259cb82
Create Date: 2026-01-25 11:14:34.275504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35d22167c2ae'
down_revision: Union[str, Sequence[str], None] = '4506a259cb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_rss_id'), table_name='youtube_rss')
    op.drop_index(op.f('ix_youtube_rss_video_id'), table_name='youtube_rss')
    op.drop_table('youtube_rss')
    op.add_column('youtube_channels', sa.Column('category', sa.String(), nullable=True))
    op.add_column('youtube_channels', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channels', 'description')
    op.drop_column('youtube_channels', 'category')
    op.create_table('youtube_rss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_rss_pkey'))
    )
    op.create_index(op.f('ix_youtube_rss_video_id'), 'youtube_rss', ['video_id'], unique=True)
    op.create_index(op.f('ix_youtube_rss_id'), 'youtube_rss', ['id'], unique=False)
    # ### end Alembic commands ###
