"""Add thumbnail_url to YoutubeChannel

Revision ID: 38d2f1fb75a9
Revises: 35d22167c2ae
Create Date: 2026-01-25 11:50:54.473943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d2f1fb75a9'
down_revision: Union[str, Sequence[str], None] = '35d22167c2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channels', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channels', 'thumbnail_url')
    # ### end Alembic commands ###
