"""add_country_and_category_cols

Revision ID: 3d8c02a0c275
Revises: 10c8c4a3bc49
Create Date: 2026-01-25 09:08:34.465691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8c02a0c275'
down_revision: Union[str, Sequence[str], None] = '10c8c4a3bc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_list', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('youtube_list', sa.Column('category_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_list', 'category_id')
    op.drop_column('youtube_list', 'country_code')
    # ### end Alembic commands ###
