"""Add YoutubeRSS table

Revision ID: 4506a259cb82
Revises: 3d8c02a0c275
Create Date: 2026-01-25 11:02:13.145925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4506a259cb82'
down_revision: Union[str, Sequence[str], None] = '3d8c02a0c275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_rss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_rss_id'), 'youtube_rss', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_rss_video_id'), 'youtube_rss', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_rss_video_id'), table_name='youtube_rss')
    op.drop_index(op.f('ix_youtube_rss_id'), table_name='youtube_rss')
    op.drop_table('youtube_rss')
    # ### end Alembic commands ###
