"""Rename users to user and refactor youtube log tables

Revision ID: a8233c70b6cb
Revises: 9b7f2f7ca236
Create Date: 2026-01-18 20:52:30.726418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8233c70b6cb'
down_revision: Union[str, Sequence[str], None] = '9b7f2f7ca236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('youtube_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('channel_title', sa.String(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_list_id'), 'youtube_list', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_list_video_id'), 'youtube_list', ['video_id'], unique=True)
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logs_content_type'), 'user_logs', ['content_type'], unique=False)
    op.create_index(op.f('ix_user_logs_id'), 'user_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_logs_user_id'), 'user_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_youtube_logs_id'), table_name='youtube_logs')
    op.drop_index(op.f('ix_youtube_logs_video_id'), table_name='youtube_logs')
    op.drop_table('youtube_logs')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_video_interactions_id'), table_name='user_video_interactions')
    op.drop_index(op.f('ix_user_video_interactions_user_id'), table_name='user_video_interactions')
    op.drop_index(op.f('ix_user_video_interactions_video_id'), table_name='user_video_interactions')
    op.drop_table('user_video_interactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_youtube_videos_id'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    op.add_column('comments', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('comments', sa.Column('content_id', sa.String(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.create_index(op.f('ix_comments_content_id'), 'comments', ['content_id'], unique=False)
    op.create_index(op.f('ix_comments_content_type'), 'comments', ['content_type'], unique=False)
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'])
    op.drop_column('comments', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_content_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_content_id'), table_name='comments')
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'content_id')
    op.drop_column('comments', 'content_type')
    op.create_table('youtube_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_videos_pkey'))
    )
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=True)
    op.create_index(op.f('ix_youtube_videos_id'), 'youtube_videos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_video_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('watched_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_video_interactions_user_id_fkey')),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], name=op.f('user_video_interactions_video_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_video_interactions_pkey'))
    )
    op.create_index(op.f('ix_user_video_interactions_video_id'), 'user_video_interactions', ['video_id'], unique=False)
    op.create_index(op.f('ix_user_video_interactions_user_id'), 'user_video_interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_video_interactions_id'), 'user_video_interactions', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('youtube_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_logs_pkey'))
    )
    op.create_index(op.f('ix_youtube_logs_video_id'), 'youtube_logs', ['video_id'], unique=False)
    op.create_index(op.f('ix_youtube_logs_id'), 'youtube_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_user_logs_user_id'), table_name='user_logs')
    op.drop_index(op.f('ix_user_logs_id'), table_name='user_logs')
    op.drop_index(op.f('ix_user_logs_content_type'), table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_youtube_list_video_id'), table_name='youtube_list')
    op.drop_index(op.f('ix_youtube_list_id'), table_name='youtube_list')
    op.drop_table('youtube_list')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
