"""Add is_short column to youtube_list

Revision ID: d20d626e5206
Revises: 0c7db2cc67d8
Create Date: 2026-01-24 23:17:06.100208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20d626e5206'
down_revision: Union[str, Sequence[str], None] = '0c7db2cc67d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_list', sa.Column('is_short', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_list', 'is_short')
    # ### end Alembic commands ###
