"""Add novel and novel_cuts tables

Revision ID: faef00269395
Revises: 9ebdea7f2168
Create Date: 2026-01-27 21:40:09.576081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faef00269395'
down_revision: Union[str, Sequence[str], None] = '9ebdea7f2168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)
    op.create_table('novel_cuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('cut_order', sa.Integer(), nullable=False),
    sa.Column('scene_desc', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_cuts_id'), 'novel_cuts', ['id'], unique=False)
    op.drop_column('youtube_channels', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channels', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_novel_cuts_id'), table_name='novel_cuts')
    op.drop_table('novel_cuts')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
